export const countryOptions = [
  { label: "", value: null },
  { label: "Afghanistan", value: "AF" },
  { label: "Albania", value: "AL" },
  { label: "Algeria", value: "DZ" },
  { label: "Andorra", value: "AD" },
  { label: "Angola", value: "AO" },
  { label: "Antigua and Barbuda", value: "AG" },
  { label: "Argentina", value: "AR" },
  { label: "Armenia", value: "AM" },
  { label: "Australia", value: "AU" },
  { label: "Austria", value: "AT" },
  { label: "Azerbaijan", value: "AZ" },
  { label: "Bahamas", value: "BS" },
  { label: "Bahrain", value: "BH" },
  { label: "Bangladesh", value: "BD" },
  { label: "Barbados", value: "BB" },
  { label: "Belarus", value: "BY" },
  { label: "Belgium", value: "BE" },
  { label: "Belize", value: "BZ" },
  { label: "Benin", value: "BJ" },
  { label: "Bhutan", value: "BT" },
  { label: "Bolivia", value: "BO" },
  { label: "Bosnia and Herzegovina", value: "BA" },
  { label: "Botswana", value: "BW" },
  { label: "Brazil", value: "BR" },
  { label: "Brunei", value: "BN" },
  { label: "Bulgaria", value: "BG" },
  { label: "Burkina Faso", value: "BF" },
  { label: "Burundi", value: "BI" },
  { label: "Cabo Verde", value: "CV" },
  { label: "Cambodia", value: "KH" },
  { label: "Cameroon", value: "CM" },
  { label: "Canada", value: "CA" },
  { label: "Central African Republic", value: "CF" },
  { label: "Chad", value: "TD" },
  { label: "Chile", value: "CL" },
  { label: "China", value: "CN" },
  { label: "Colombia", value: "CO" },
  { label: "Comoros", value: "KM" },
  { label: "Congo (Congo-Brazzaville)", value: "CG" },
  { label: "Congo (Congo-Kinshasa)", value: "CD" },
  { label: "Costa Rica", value: "CR" },
  { label: "Croatia", value: "HR" },
  { label: "Cuba", value: "CU" },
  { label: "Cyprus", value: "CY" },
  { label: "Czechia", value: "CZ" },
  { label: "Denmark", value: "DK" },
  { label: "Djibouti", value: "DJ" },
  { label: "Dominica", value: "DM" },
  { label: "Dominican Republic", value: "DO" },
  { label: "Ecuador", value: "EC" },
  { label: "Egypt", value: "EG" },
  { label: "El Salvador", value: "SV" },
  { label: "Equatorial Guinea", value: "GQ" },
  { label: "Eritrea", value: "ER" },
  { label: "Estonia", value: "EE" },
  { label: "Eswatini", value: "SZ" },
  { label: "Ethiopia", value: "ET" },
  { label: "Fiji", value: "FJ" },
  { label: "Finland", value: "FI" },
  { label: "France", value: "FR" },
  { label: "Gabon", value: "GA" },
  { label: "Gambia", value: "GM" },
  { label: "Georgia", value: "GE" },
  { label: "Germany", value: "DE" },
  { label: "Ghana", value: "GH" },
  { label: "Greece", value: "GR" },
  { label: "Grenada", value: "GD" },
  { label: "Guatemala", value: "GT" },
  { label: "Guinea", value: "GN" },
  { label: "Guinea-Bissau", value: "GW" },
  { label: "Guyana", value: "GY" },
  { label: "Haiti", value: "HT" },
  { label: "Honduras", value: "HN" },
  { label: "Hungary", value: "HU" },
  { label: "Iceland", value: "IS" },
  { label: "India", value: "IN" },
  { label: "Indonesia", value: "ID" },
  { label: "Iran", value: "IR" },
  { label: "Iraq", value: "IQ" },
  { label: "Ireland", value: "IE" },
  { label: "Israel", value: "IL" },
  { label: "Italy", value: "IT" },
  { label: "Jamaica", value: "JM" },
  { label: "Japan", value: "JP" },
  { label: "Jordan", value: "JO" },
  { label: "Kazakhstan", value: "KZ" },
  { label: "Kenya", value: "KE" },
  { label: "Kiribati", value: "KI" },
  { label: "Kuwait", value: "KW" },
  { label: "Kyrgyzstan", value: "KG" },
  { label: "Laos", value: "LA" },
  { label: "Latvia", value: "LV" },
  { label: "Lebanon", value: "LB" },
  { label: "Lesotho", value: "LS" },
  { label: "Liberia", value: "LR" },
  { label: "Libya", value: "LY" },
  { label: "Liechtenstein", value: "LI" },
  { label: "Lithuania", value: "LT" },
  { label: "Luxembourg", value: "LU" },
  { label: "Madagascar", value: "MG" },
  { label: "Malawi", value: "MW" },
  { label: "Malaysia", value: "MY" },
  { label: "Maldives", value: "MV" },
  { label: "Mali", value: "ML" },
  { label: "Malta", value: "MT" },
  { label: "Mexico", value: "MX" },
  { label: "Moldova", value: "MD" },
  { label: "Monaco", value: "MC" },
  { label: "Mongolia", value: "MN" },
  { label: "Montenegro", value: "ME" },
  { label: "Morocco", value: "MA" },
  { label: "Mozambique", value: "MZ" },
  { label: "Myanmar", value: "MM" },
  { label: "Namibia", value: "NA" },
  { label: "Nepal", value: "NP" },
  { label: "Netherlands", value: "NL" },
  { label: "New Zealand", value: "NZ" },
  { label: "Nicaragua", value: "NI" },
  { label: "Niger", value: "NE" },
  { label: "Nigeria", value: "NG" },
  { label: "North Korea", value: "KP" },
  { label: "Norway", value: "NO" },
  { label: "Oman", value: "OM" },
  { label: "Pakistan", value: "PK" },
  { label: "Panama", value: "PA" },
  { label: "Peru", value: "PE" },
  { label: "Philippines", value: "PH" },
  { label: "Poland", value: "PL" },
  { label: "Portugal", value: "PT" },
  { label: "Qatar", value: "QA" },
  { label: "Romania", value: "RO" },
  { label: "Russia", value: "RU" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "South Africa", value: "ZA" },
  { label: "United States", value: "US" },
];


export const commonJobs = [
  { id: 1, label: "Software Engineer" },
  { id: 2, label: "Doctor" },
  { id: 3, label: "Nurse" },
  { id: 4, label: "Teacher" },
  { id: 5, label: "Accountant" },
  { id: 6, label: "Electrician" },
  { id: 7, label: "Plumber" },
  { id: 8, label: "Construction Worker" },
  { id: 9, label: "Police Officer" },
  { id: 10, label: "Firefighter" },
  { id: 11, label: "Chef" },
  { id: 12, label: "Waiter/Waitress" },
  { id: 13, label: "Graphic Designer" },
  { id: 14, label: "Marketing Manager" },
  { id: 15, label: "Sales Representative" },
  { id: 16, label: "Customer Service Representative" },
  { id: 17, label: "Human Resources Manager" },
  { id: 18, label: "IT Support Specialist" },
  { id: 19, label: "Truck Driver" },
  { id: 20, label: "Mechanic" },
  { id: 21, label: "Dentist" },
  { id: 22, label: "Pharmacist" },
  { id: 23, label: "Veterinarian" },
  { id: 24, label: "Bank Teller" },
  { id: 25, label: "Financial Analyst" },
  { id: 26, label: "Security Guard" },
  { id: 27, label: "Journalist" },
  { id: 28, label: "Photographer" },
  { id: 29, label: "Architect" },
  { id: 30, label: "Real Estate Agent" },
  { id: 31, label: "Social Worker" },
  { id: 32, label: "Paralegal" },
  { id: 33, label: "Lawyer" },
  { id: 34, label: "Barber" },
  { id: 35, label: "Hairdresser" },
  { id: 36, label: "Pilot" },
  { id: 37, label: "Flight Attendant" },
  { id: 38, label: "Warehouse Worker" },
  { id: 39, label: "Scientist" },
  { id: 40, label: "Psychologist" },
  { id: 41, label: "Data Analyst" },
  { id: 42, label: "Data Scientist" },
  { id: 43, label: "Software Tester" },
  { id: 44, label: "Cybersecurity Analyst" },
  { id: 45, label: "UX/UI Designer" },
  { id: 46, label: "Web Developer" },
  { id: 47, label: "Mobile App Developer" },
  { id: 48, label: "Game Developer" },
  { id: 49, label: "AI Engineer" },
  { id: 50, label: "Machine Learning Engineer" },
  { id: 51, label: "Biologist" },
  { id: 52, label: "Chemist" },
  { id: 53, label: "Physicist" },
  { id: 54, label: "Mathematician" },
  { id: 55, label: "Astronomer" },
  { id: 56, label: "Historian" },
  { id: 57, label: "Professor" },
  { id: 58, label: "Librarian" },
  { id: 59, label: "Event Planner" },
  { id: 60, label: "Actor" },
  { id: 61, label: "Musician" },
  { id: 62, label: "Athlete" },
  { id: 63, label: "Coach" },
  { id: 64, label: "Personal Trainer" },
  { id: 65, label: "Dietitian" },
  { id: 66, label: "Zookeeper" },
  { id: 67, label: "Dog Trainer" },
  { id: 68, label: "Farmer" },
  { id: 69, label: "Fisherman" },
  { id: 70, label: "Baker" },
  { id: 71, label: "Butcher" },
  { id: 72, label: "Cashier" },
  { id: 73, label: "Retail Manager" },
  { id: 74, label: "Janitor" },
  { id: 75, label: "Housekeeper" },
  { id: 76, label: "Mail Carrier" },
  { id: 77, label: "Courier" },
  { id: 78, label: "Translator" },
  { id: 79, label: "Interpreter" },
  { id: 80, label: "Tour Guide" },
  { id: 81, label: "Bus Driver" },
  { id: 82, label: "Train Conductor" },
  { id: 83, label: "Carpenter" },
  { id: 84, label: "Roofer" },
  { id: 85, label: "Welder" },
  { id: 86, label: "Painter" },
  { id: 87, label: "Real Estate Broker" },
  { id: 88, label: "Stock Trader" },
  { id: 89, label: "Economist" },
  { id: 90, label: "Entrepreneur" },
  { id: 91, label: "Consultant" },
  { id: 92, label: "Park Ranger" },
  { id: 93, label: "Environmental Scientist" },
  { id: 94, label: "Meteorologist" },
  { id: 95, label: "Geologist" },
  { id: 96, label: "Urban Planner" },
  { id: 97, label: "Political Analyst" },
  { id: 98, label: "Diplomat" },
  { id: 99, label: "Pastor" },
  { id: 100, label: "Military Officer" }
];

export const commonCompanies = [
  { id: 1, label: "Google" },
  { id: 2, label: "Apple" },
  { id: 3, label: "Microsoft" },
  { id: 4, label: "Amazon" },
  { id: 5, label: "Facebook" },
  { id: 6, label: "Tesla" },
  { id: 7, label: "Netflix" },
  { id: 8, label: "Adobe" },
  { id: 9, label: "IBM" },
  { id: 10, label: "Intel" },
  { id: 11, label: "Nvidia" },
  { id: 12, label: "Samsung" },
  { id: 13, label: "Sony" },
  { id: 14, label: "LG" },
  { id: 15, label: "Cisco" },
  { id: 16, label: "Oracle" },
  { id: 17, label: "Salesforce" },
  { id: 18, label: "SAP" },
  { id: 19, label: "Dell" },
  { id: 20, label: "HP" },
  { id: 21, label: "Uber" },
  { id: 22, label: "Lyft" },
  { id: 23, label: "Airbnb" },
  { id: 24, label: "Spotify" },
  { id: 25, label: "Twitter" },
  { id: 26, label: "Snapchat" },
  { id: 27, label: "TikTok" },
  { id: 28, label: "Pinterest" },
  { id: 29, label: "Reddit" },
  { id: 30, label: "PayPal" },
  { id: 31, label: "Visa" },
  { id: 32, label: "Mastercard" },
  { id: 33, label: "Stripe" },
  { id: 34, label: "Square" },
  { id: 35, label: "Shopify" },
  { id: 36, label: "eBay" },
  { id: 37, label: "Alibaba" },
  { id: 38, label: "Tencent" },
  { id: 39, label: "Baidu" },
  { id: 40, label: "Xiaomi" },
  { id: 41, label: "Huawei" },
  { id: 42, label: "Lenovo" },
  { id: 43, label: "AMD" },
  { id: 44, label: "Qualcomm" },
  { id: 45, label: "Broadcom" },
  { id: 46, label: "Texas Instruments" },
  { id: 47, label: "Twitter" },
  { id: 48, label: "Dropbox" },
  { id: 49, label: "Slack" },
  { id: 50, label: "Zoom" },
  { id: 51, label: "WeWork" },
  { id: 52, label: "Robinhood" },
  { id: 53, label: "Coinbase" },
  { id: 54, label: "Binance" },
  { id: 55, label: "BitPay" },
  { id: 56, label: "Roku" },
  { id: 57, label: "Disney" },
  { id: 58, label: "Warner Bros." },
  { id: 59, label: "Paramount" },
  { id: 60, label: "Universal" },
  { id: 61, label: "Fox" },
  { id: 62, label: "HBO" },
  { id: 63, label: "BBC" },
  { id: 64, label: "CNN" },
  { id: 65, label: "The New York Times" },
  { id: 66, label: "The Washington Post" },
  { id: 67, label: "Forbes" },
  { id: 68, label: "Bloomberg" },
  { id: 69, label: "Reuters" },
  { id: 70, label: "Nike" },
  { id: 71, label: "Adidas" },
  { id: 72, label: "Puma" },
  { id: 73, label: "Under Armour" },
  { id: 74, label: "Reebok" },
  { id: 75, label: "New Balance" },
  { id: 76, label: "Asics" },
  { id: 77, label: "Lululemon" },
  { id: 78, label: "Gucci" },
  { id: 79, label: "Prada" },
  { id: 80, label: "Louis Vuitton" },
  { id: 81, label: "Chanel" },
  { id: 82, label: "Hermès" },
  { id: 83, label: "Rolex" },
  { id: 84, label: "Omega" },
  { id: 85, label: "Patek Philippe" },
  { id: 86, label: "Cartier" },
  { id: 87, label: "Boeing" },
  { id: 88, label: "Airbus" },
  { id: 89, label: "Lockheed Martin" },
  { id: 90, label: "SpaceX" },
  { id: 91, label: "Blue Origin" },
  { id: 92, label: "NASA" },
  { id: 93, label: "General Electric" },
  { id: 94, label: "Siemens" },
  { id: 95, label: "Honeywell" },
  { id: 96, label: "Phillips" },
  { id: 97, label: "3M" },
  { id: 98, label: "Johnson & Johnson" },
  { id: 99, label: "Pfizer" },
  { id: 100, label: "Moderna" }
];


export const employeeRanges = [
  { id: 1, label: "1-50" },
  { id: 2, label: "50-100" },
  { id: 3, label: "100-200" },
  { id: 4, label: "200-500" },
  { id: 5, label: "500-1000" },
  { id: 6, label: "1000-2000" },
  { id: 7, label: "2000+" }
];
